version: '3.6'
services:
  iris:
    init: true
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 51773:1972
      - 52773:52773
      - 53773:53773
    volumes:
      - ./:/irisdev/app
